@extends('frontend.layout')

@section('title', 'terms')

{{-- @section('header')
  @include('library.modules.header')
@endsection --}}

@section('content')
  <div class="outer-container">
    <div class="inner-container">
      <h2 class="section-title">
        Terms of Service
      </h2>

      <span class="section-subtitle">
        Privacy policy
      </span>

      <p class="section-text">
We respect your personal data and do our best to protect it. SEEK Athletics
will only collect, process and use your personal data in compliance with the
provisions of this Privacy Policy and the applicable data protection legislation.
A. Data controller
The party responsible for the operation of the SEEK Athletics website
(www.seek-athletics.com) is Christian Fleck, Sonnwendgasse 18, 2295
Oberweiden, Austria (“SEEK Athletics”).
B. Your personal data
Personal data means any information concerning an identified or identifiable
individual. Such data includes, for example, your name, your telephone
number as well as your postal and e-mail addresses.
C. Data processing by SEEK Athletics
SEEK Athletics will only collect, process and use your personal data to the
extent described below.
I. Newsletter
If you have subscribed to the SEEK Athletics newsletter, SEEK Athletics will
only use your personal information for the purpose of sending the requested
newsletter to you. If you cancel your subscription to a newsletter, your data will
be deleted without delay. You can cancel the subscription at any time by
clicking the related link in each newsletter.

II. Contests and campaigns
You may also have the opportunity to take part in contests or other campaigns
conducted by SEEK Athletics. Where you are required to provide your
personal data (e.g. your name, e-mail address, postal address, etc.) for the
purpose of taking part in such contests or campaigns, SEEK Athletics will only
use this data for the purposes of conducting the contest or other campaign and
only in compliance with the applicable terms and conditions. If you have
expressly consented to being sent newsletters, SEEK Athletics will send
newsletters to you as described in section C. I. Neither your participation in a
contest nor your chances of winning will be affected should you not consent to
receiving newsletters or should you revoke your consent at a later time.
III. Cookies and web beacons
Web cookies are small pieces of data sent by websites which are stored by
your browser on your computer&#39;s hard drive. The use of cookies enables us to
determine which country you are in and recognise you when you visit the
Website again. In addition some cookies will be sent by third parties, which for
example enable us to have SEEK Athletics products that reflect your interests
offered to you on our partners&#39; websites (known as retargeting).

You can also block cookies in your browser’s settings. However, if you do so,
some areas of the Website may no longer function properly.

SEEK Athletics also uses web beacons (pixel tags). When you open a page on
the Website, this pixel will be downloaded from a server and registered. This
enables us to determine which pages were viewed when and how often, as
well as what actions were undertaken on these pages, for instance.
IV. Use of web analysis tools
This Website uses Google Analytics, a web analysis service from Google Inc.
in the US (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA,
“Google”). Google Analytics uses cookies, which are text files saved on your
computer to enable analysis of your use of the Website. The information

generated by the cookie about your use of this Website (including your IP
address) is transmitted to a Google server in the US, where it is saved. Google
use this information to analyse your use of the Website, to compile reports for
SEEK Athletics about your related activities and to provide other services
connected with the use of the Website and the internet. Google may also
transfer this information to third parties if prescribed by law or if third parties
process this data on behalf of Google. Google will in no event link your IP
address with other Google data. You can block cookies with a particular
setting on your browser; however, in this case you will not be able to use all
functions of this Website in full. Please note that SEEK Athletics uses Google
Analytics with the “_anonymizeIp()” extension so that your IP address is
processed only in an abbreviated form to rule out a direct reference to any
person.

You can revoke your consent to the collection and use of information by
Google at any time with future effect by installing the Google Opt-out Browser
Add-on.
V. Social Plugins
The Website contains social plugins from Facebook, Google and Twitter (the
Facebook &#39;Like&#39; button, the &#39;Google +1&#39; button and the Twitter button). These
are offered by the American companies Facebook Inc. (1601 S. California Ave,
Palo Alto, CA 94304, USA), Google Inc. (1600 Amphitheatre Parkway,
Mountain View, CA 94043, USA) and Twitter Inc. (795 Folsom St., Suite 600,
San Francisco, CA 94107, USA). If you visit a website containing such a
plugin, your browser can establish a direct connection with the servers of
Facebook, Google or Twitter and transmit data about your surfing behaviour to
the servers of Facebook, Google or Twitter (e.g. even if you do not click the
“Like” button). If you are logged into one of the social media sites, Facebook,
Google or Twitter can assign the visit to your social media account. SEEK
Athletics has no influence on the type and scope of the data collected and

transmitted. For further information on protecting your privacy, see the relevant
websites: Facebook, Google, Twitter.

Last updated: 18 February 2017
      </p>
    </div>
  </div>
@endsection

@section('footer')
  @include('library.modules.footer')
@endsection
